---
# tasks file for zabbix
- debug: msg="Will install phpldap & configure it"

- name: phpldap install
  yum: name=phpldapadmin state=latest

- name: httpd configuration file for phpLDAPadmin
  replace: 
   dest=/etc/httpd/conf.d/phpldapadmin.conf
   regexp={{item.regexp}}
   replace={{item.replace}}
  with_items:
   - {regexp: 'Order Deny,Allow', replace: 'Order Allow,Deny'}
   - {regexp: 'Allow from 127.0.0.1', replace: 'Allow from 192.168.25.1'}
   - {regexp: 'Deny from all', replace: 'Deny from 127.0.0.1'}

- name: edit main configuration file of phpldapadmin
  replace: 
   dest=/etc/phpldapadmin/config.php
   regexp={{item.regexp}}
   replace={{item.replace}}
  with_items:
   - {regexp: '$servers->setValue('login','attr','dn');', replace: '#$servers->setValue('login','attr','dn');'}
   - {regexp: '//$servers->setValue('login','attr','uid');', replace: '#//$servers->setValue('login','attr','uid');'}

- name: Start httpd server
  service: name=httpd state=started enabled=yes
  
